# theme: jekyll-theme-tactile
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Lead Architect & AI Solutions Specialist | Cloud, Microservices & AI Expert
description: AWS Certified Solution Architect | Lead Technical Architect (11+ years) specializing in cloud management platforms, AI-driven applications, and microservices.  Hands-on expertise in FastAPI, Python, Kubernetes, OpenStack, Java, and Spring Boot. Led development of Cirrus Cloud Platform (CCP) and the Government of India's Health ID initiative. I enjoy building scalable solutions and working closely with clients to achieve their goals.

github:  
  owner_url: https://github.com/DeepakPant93  
  is_project_page: false
  show_downloads: false
